#!/usr/bin/env python3
"""Build paper/paper.bib from references.yaml, using doi.org's BibTeX API.

For each entry with a `doi`, fetch the BibTeX record from doi.org (content negotiation,
`Accept: application/x-bibtex`), then:
  - replace doi.org's generated key with the key from references.yaml,
  - keep only the fields in KEEP, lower-case the field names,
  - turn en dashes in page ranges into `--`,
  - brace each word listed in `protect`, so the citation style keeps its case,
  - apply `override` fields.
Entries with `type` and `fields` instead of a `doi` are written as given (after `protect`).

Usage: python3 tools/make_bib.py [references.yaml] [paper/paper.bib]
Needs PyYAML. Run from anywhere; default paths are relative to the repository root.
"""
import re
import sys
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
KEEP = ["title", "author", "journal", "booktitle", "publisher", "volume", "number", "pages",
        "year", "doi", "howpublished", "note"]


def fetch_bibtex(doi):
    req = urllib.request.Request(f"https://doi.org/{doi}",
                                 headers={"Accept": "application/x-bibtex; charset=utf-8"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8")


def parse_bibtex(text):
    """Parse one BibTeX entry into (type, fields). Values may be {braced} or bare."""
    m = re.match(r"\s*@(\w+)\s*\{\s*[^,]*,", text)
    if not m:
        raise ValueError(f"not a BibTeX entry: {text[:80]!r}")
    entry_type, pos, fields = m.group(1).lower(), m.end(), {}
    while True:
        m = re.compile(r"\s*(\w+)\s*=\s*").match(text, pos)
        if not m:
            break
        name, pos = m.group(1).lower(), m.end()
        if text[pos] == "{":
            depth, start = 0, pos
            for pos in range(start, len(text)):
                depth += {"{": 1, "}": -1}.get(text[pos], 0)
                if depth == 0:
                    break
            value, pos = text[start + 1:pos], pos + 1
        else:
            m = re.compile(r"[^,}\s]+").match(text, pos)
            value, pos = m.group(0), m.end()
        fields[name] = value.strip()
        m = re.compile(r"\s*,?").match(text, pos)
        pos = m.end()
    return entry_type, fields


def protect(title, words):
    for word in words:
        title = re.sub(rf"(?<![{{\w-]){re.escape(word)}(?![}}\w-])", "{" + word + "}", title)
    return title


def build_entry(key, spec):
    if "doi" in spec:
        entry_type, fields = parse_bibtex(fetch_bibtex(spec["doi"]))
        fields = {k: v for k, v in fields.items() if k in KEEP}
        if "pages" in fields:
            fields["pages"] = fields["pages"].replace("–", "--")
    else:
        entry_type, fields = spec["type"], {k: str(v) for k, v in spec["fields"].items()}
    fields.update({k: str(v) for k, v in (spec.get("override") or {}).items()})
    if "title" in fields:
        fields["title"] = protect(fields["title"], spec.get("protect", []))
    order = [k for k in KEEP if k in fields] + [k for k in fields if k not in KEEP]
    width = max(len(k) for k in order)
    body = ",\n".join(f"  {k:<{width}} = {{{fields[k]}}}" for k in order)
    return f"@{entry_type}{{{key},\n{body}\n}}\n"


def main():
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "references.yaml"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "paper" / "paper.bib"
    refs = yaml.safe_load(src.read_text())
    entries = []
    for key, spec in refs.items():
        print(f"{key}: {spec.get('doi', spec.get('type'))}", file=sys.stderr)
        entries.append(build_entry(key, spec))
    header = ("@comment{Generated by tools/make_bib.py from references.yaml. "
              "Do not edit by hand; edit references.yaml and re-run the script.}\n\n")
    out.write_text(header + "\n".join(entries))
    print(f"wrote {len(entries)} entries to {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
